### ISSUE TITLE
Noto Sans Sundanese: Double vowel signs messed up 

### ISSUE THREAD

**Issue by Ilhamkang** [googlei18n/noto-fonts#959]
I found some rendering problem for double signs messed up above a consonant and front-above consonant. Here's the sample: 

![render-word](https://user-images.githubusercontent.com/22653757/29765528-b9a42c1e-8c05-11e7-92e5-edf32574e99e.png)
(above: Noto Sans Sundanese, below: "Sundanese Unicode" font by Unicode Aksara Sunda team in West Java). Correct rendering should looks like the below image.

The phrase should read "deungkleung déngdék", with typing sequence: 
da+eu+anusvara+ka+subjoined la+eu+anusvara da+ae+anusvara+da+ae+ka+virama

I've reviewed the issue before here: 
https://goo.gl/SnqH1F

**Comment by r12a** [comment]
A particularly serious issue, which is not clearly mentioned above is the right-side positioning of the eu vowel-sign. It should be to the left. Should i raise a separate issue for that?

fwiw, you can test different fonts with the sequence at 
https://r12a.github.io/pickers/sundanese/?text=%E1%AE%93%E1%AE%A9%E1%AE%80%E1%AE%8A%E1%AE%A3%E1%AE%A9%E1%AE%80%20%E1%AE%93%E1%AE%A6%E1%AE%80%E1%AE%93%E1%AE%A6%E1%AE%8A%E1%AE%AA

Sundanese Unicode 2013 positions it correctly. Noto Sans Sundanese doesn't.

**Comment by Ilhamkang** [comment]
Yes, indeed. The **eu** vowel-sign should move to the left, so the double sign will be center-aligned above the consonant. Here are positioning samples of signs.
![positioning](https://user-images.githubusercontent.com/22653757/29824629-396df334-8cfc-11e7-9ec6-3e5a042f904f.jpg)

I've reproduced various sequences with double and triple signs combination here: 
https://r12a.github.io/pickers/sundanese/?text=%E1%AE%98%E1%AE%A3%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A4%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A5%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A8%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A9%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A7%E1%AE%80%20%E1%AE%98%E1%AE%A3%E1%AE%A6%E1%AE%80%20%20%20%0Ablang%2C%20bling%2C%20blung%2C%20bleng%2C%20bleung%2C%20blong%2C%20bl%C3%A9ng%20%0A%E1%AE%98%E1%AE%A1%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A4%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A5%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A8%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A9%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A7%E1%AE%80%20%E1%AE%98%E1%AE%A1%E1%AE%A6%E1%AE%80%20%0Abyang%2C%20bying%2C%20byung%2C%20byeng%2C%20byeung%2C%20byong%2C%20by%C3%A9ng%0A%E1%AE%98%E1%AE%A2%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A4%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A5%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A8%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A9%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A7%E1%AE%80%20%E1%AE%98%E1%AE%A2%E1%AE%A6%E1%AE%80%20%0Abrang%2C%20bring%2C%20brung%2C%20breng%2C%20breung%2C%20brong%2C%20br%C3%A9ng

Again, Sundanese Unicode 2013 renders them correctly, but Noto Sans Sundanese does not.

**Comment by marekjez86** [comment]
[NotoSansSundanese-Regular.otf.zip](https://github.com/googlei18n/noto-fonts/files/1516412/NotoSansSundanese-Regular.otf.zip)

@Ilhamkang , @r12a : could you verify that it was fixed in the font above? Thank you

**Comment by marekjez86** [comment]
@Ilhamkang : thank you! we'll investigate it

**Comment by marekjez86** [comment]
The text:
 ᮘᮢᮧᮀ ᮘᮣᮧᮀ ᮘᮡᮧᮀ

Expected 

![sund-959-expected](https://user-images.githubusercontent.com/13322623/33586502-84784e7e-d91e-11e7-9d32-5e2f3c723094.jpeg)

Noto

![sund-959-noto](https://user-images.githubusercontent.com/13322623/33586508-8cddd0ca-d91e-11e7-8698-4ecca0a29146.jpeg)

**Comment by nizarsq** [comment]
The issue with the triple sign sequences still reproducible
<img width="1229" alt="Screen Shot 2020-08-08 at 9 53 56 PM" src="https://user-images.githubusercontent.com/22158882/89725177-aba73900-d9c1-11ea-9cb5-ae47813814cd.png">
